### ISSUE TITLE
Live lookup status reports failure when it's not failing

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/library-status#391]
Fallout from migration to FOLIO?

**Comment by jcoyne** [comment]
fixed by https://github.com/sul-dlss/library-status/pull/390 ?

**Comment by thatbudakguy** [comment]
doesn't look like it:

![Screenshot 2023-09-01 at 10 41 37](https://github.com/sul-dlss/library-status/assets/4924494/321b67b5-39eb-45d7-a459-ddca705399d9)
